jobs:
    test-job:
        image: node:20
        steps:
            - echo: echo 'this is test job.'
        requires: [~commit, ~pr]
    tag-triggered-job:
        requires: [~commit]
        image: node:20
        steps:
            - echo: |
                echo 'this job is executed by a tag push event.'
    release-triggered-job:
        image: node:20
        steps:
            - echo: |
                echo 'this job is executed by a release push event.'
        requires: [~release]
    combo-triggered-job:
        image: node:20
        steps:
            - echo: |
                echo 'this job is executed by a tag/release push event.'
        #requires: [~release, ~tag]
        requires: [~commit, ~pr]
    tag-branch-triggered-job:
        image: node:20
        steps:
            - echo: |
                echo 'this job is executed by a tag push event.'
        requires: [~tag:/^v\.*/]       
